### ISSUE TITLE
Arithmetic tests don't pass with other fields

### ISSUE THREAD

**Issue by DanieleDiBenedetto** [arkworks-rs/nonnative#32]
I was running the unit tests for different field pairs configurations than the ones already tested in `tests/arithmetic_tests.rs`, and several tests are failing. In particular, I added:

```
use ark_pallas::{Fr, Fq};
nonnative_test!(
    PallasFrMNT6Fr,
    Fr,
    <MNT6_753 as PairingEngine>::Fr
);
nonnative_test!(
    MNT6FrPallasFr,
    <MNT6_753 as PairingEngine>::Fr
    Fr
);
nonnative_test!(
    PallasFqFr,
    Fq,
    Fr
);
nonnative_test!(
    PallasFrFq,
    Fr,
    Fq
);
```

The failures are the following:

```
cargo test pallasfqfr

test double_stress_test_2_pallasfqfr ... FAILED
test double_stress_test_3_pallasfqfr ... FAILED

failures:

---- double_stress_test_2_pallasfqfr stdout ----
thread 'double_stress_test_2_pallasfqfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

---- double_stress_test_3_pallasfqfr stdout ----
thread 'double_stress_test_3_pallasfqfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

```

And it's the same also if I test for `pallasfrfq` ; Interestingly, if I enable the `density-optimized` feature, all the tests run succesfully.

Regarding the other pair of fields, all the test fails with the very same error, either I enable the `density-optimized` feature or not:

```
cargo test pallasfrmnt6fr

thread '...' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Daniele Di Benedetto\Documents\nonnative\src\allocated_nonnative_field_var.rs:45:67
```
 
I got yet another different result by running:

```
cargo test mnt6frpallasfr 

test equality_test_mnt6frpallasfr ... FAILED
test double_stress_test_2_mnt6frpallasfr ... FAILED
test double_stress_test_3_mnt6frpallasfr ... FAILED

failures:

---- equality_test_mnt6frpallasfr stdout ----
thread 'equality_test_mnt6frpallasfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

---- double_stress_test_2_mnt6frpallasfr stdout ----
thread 'double_stress_test_2_mnt6frpallasfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

---- double_stress_test_3_mnt6frpallasfr stdout ----
thread 'double_stress_test_3_mnt6frpallasfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

```
And  if enable the `density-optimized` feature:

```
cargo test mnt6frpallasfr --features "density-optimized"

test double_stress_test_2_mnt6frpallasfr ... FAILED
test double_stress_test_3_mnt6frpallasfr ... FAILED

failures:

---- double_stress_test_2_mnt6frpallasfr stdout ----
thread 'double_stress_test_2_mnt6frpallasfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

---- double_stress_test_3_mnt6frpallasfr stdout ----
thread 'double_stress_test_3_mnt6frpallasfr' panicked at 'assertion failed: cs.is_satisfied().unwrap()', tests\arithmetic_tests.rs:695:1

```

Am I misusing the library in some way ? Thanks in advance !

**Comment by weikengchen** [comment]
I think you are using it correctly, but an unknown bug pops up.

I will debug it today. Thanks for lettinng us know this!
